branches:
  only:
    - wheels

language: cpp

sudo: true

matrix:
  allow_failures:
    - os: osx

  include:
    - language: python
      sudo: false
      python: 2.7
      env: TASKS="clang-format"

      os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          packages:
          - clang-format-6.0
      if: branch = master
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.9
      env:
        - TASKS="ctest gcc-4.9"
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      if: branch = master
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env:
        - TASKS="ctest gcc-6.3"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      if: branch = master
    - compiler: clang
      os: linux
      env: TASKS="ctest clang-3.9"
      if: branch = master
    - os: osx
      env: TASKS="Mac clang"
      if: branch = master

    - os: osx
      env: DEPLOY=TRUE


install: true
#  - . ./scripts/travis/install.sh

script: true
#  - ./scripts/travis/build.sh

before_deploy:
  - ./scripts/travis/deploy.sh

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  username: openchemistry
  password:
    secure: a2lzXcO8JZvUMTtZ8avD4uJc6CeNavzkg6yTHeIdN+A/GhIdaPezqgtu6ZZTdy7eyLJBm4/crjvtI3RhX3ew0tmXJzHLepdknu2i94dRJqHJxAARdkU/h61p707HZOudSMikl8g1V3FjVgHOhKd0dym3Lw+ZxuydoTJEOmjM55kcUJuyncx/s/XnSPwcaih9fP7mrYewtcMXkYs1qzEBpdRJ2PiXbUA3kq9lJC624tsR7zz0/afOZt2wDKFhS4D2ijHuwo0YrxEPBNNhVz3FehEDfB1tx3H+nvUHAjEBCtix/wpLu5uEx3v1bf1m65mihcTPS8jF+brn1DiknjrrLauSYD8BjyKZKYrbJw5vFLWjCOlg4k/tS7bbIWdyHSUaU2wyrjulveW8rWBpicrsTZksUWTawZkRFldb70UZDAWbNgcT5P+wXimFYv1BQaVV+EM8SyZ8Do4s2PvH/lck64BRK3cBwhdEvSfloMAbk9NRqlb8L1xGPoLt7bvhj7eyZkVmT+ma0tYTuoMz3xxLSqqDNgjyCmqgBtQ4XFlg3kSA5K9lwxAE3fdymUvXol8ahxSK/Aglv1amZO3GIsDNS78xEtH69Pr5GN0WAClfJ8AS7TeTG5maSpCkk3ZfTG8qO1bbvQzr6i1kBttyajJODU+YgmD494SedNaZ9JeCqZs=
  distributions: "bdist_wheel"
  skip_cleanup: true
  on:
    branch: wheels
    condition: $DEPLOY=TRUE

